### ISSUE TITLE
Ajout de macros katex via gist id

### ISSUE THREAD

**Issue by franckyboy** [lgarcin/EulerBot#1]
Bonjour, 
Merci d'avoir développé ce bot de qualité ! J'ai un petit problème pour ajouter des macros à katex (en utilisant votre gist) comme expliqué sur la page d'accueil: si j'écris

!katex gistd 2b99c0da9182b736f3d5f646e1b99cde

Euler me retourne Wrong Gist id; pourtant je crois avoir bien recopié votre gist id.

**Comment by lgarcin** [comment]
Bonjour,
Il y a une coquille dans la doc que je vais corriger.
Il faut taper
```
!katex 2b99c0da9182b736f3d5f646e1b99cde
```

**Comment by franckyboy** [comment]
Ça marche, merci beaucoup !
