### ISSUE TITLE
Bot crashes when running the following code

### ISSUE THREAD

**Issue by franckyboy** [lgarcin/EulerBot#6]
Hi, 
The following Koch fractal Python code makes the Euler Bot crash (rendering it offline for a minute):
```
!python
import matplotlib.pyplot as plt
from numpy import cos, pi
plt.axis([-0.1, 1.1, -0.1, 0.5])
def courbe(A,B,n):
    if n == 0:
        plt.plot([A[0],B[0]],[A[1],B[1]],color='r')
    else:
        AB = [ B[0] - A[0] , B[1] - A[1] ]   
        A1 = [ A[0] + AB[0]/3 , A[1] + AB[1]/3 ]
        N  = [ -AB[1] , AB[0] ]
        A2 = [ A[0] + AB[0]/2 + cos(pi/6)*N[0]/3 , A[1] + AB[1]/2 + cos(pi/6)*N[1]/3]
        A3 = [ A[0] + 2*AB[0]/3 , A[1] + 2*AB[1]/3 ]
        courbe(A,A1,n-1)
        courbe(A1,A2,n-1)
        courbe(A2,A3,n-1)
        courbe(A3,B,n-1)       
courbe([0,0],[1,0],3)
plt.show()
```

I am not sure what causes this. I noted that the asterisks are interpreted as italic and thus the code does not display well on discord before being processed by Euler, but this was not problem for other things such as print(2\*3\*4)

**Comment by lgarcin** [comment]
I can indeed reproduce your problem. I am investigating this issue.

**Comment by lgarcin** [comment]
I think it's fixed. It had to do with recursice calls in `exec`.
https://stackoverflow.com/questions/871887/using-exec-with-recursive-functions/

**Comment by franckyboy** [comment]
Yes it works now, thanks ! Out of curiosity which changes did you make so that it now works ?

**Comment by lgarcin** [comment]
Python code is executed by the bot in a sandboxed environment by the `exec` function. The issue with recursive functions is detailed in this SO post.
https://stackoverflow.com/a/872082/4439374
I only had to replace `exec(code)` by `exec(code,locals(),locals())` where `code` is the code inputted by the discord user.

**Comment by franckyboy** [comment]
OK, thanks !
